name: Test & Release Terraform Module

on:
  workflow_call:
    inputs: {}
    secrets: {}
    # The caller workflow will provide permissions

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init & Validate
        run: |
          terraform init -backend=false
          terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v3

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Run TFLint
        run: tflint --disable-rule=terraform_required_providers --disable-rule=terraform_required_version

  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip install checkov
          checkov --version

      - name: Run Checkov
        run: checkov -d . --skip-path .github

  release:
    name: Release ${{ github.event.repository.name }} Module
    runs-on: ubuntu-latest
    needs: [terraform, tflint, checkov]
    permissions:
      contents: write     # Needed to push tags

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "last_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Calculate next tag
        id: bump
        run: |
          LAST=${{ steps.get_tag.outputs.last_tag }}
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LAST#v}"
          PATCH=$((PATCH+1))
          NEXT="v$MAJOR.$MINOR.$PATCH"
          echo "next_tag=$NEXT" >> $GITHUB_OUTPUT

      - name: Authenticate git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Create new tag
        run: |
          git tag ${{ steps.bump.outputs.next_tag }}
          git push origin ${{ steps.bump.outputs.next_tag }}

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.next_tag }}
